---
galaxy_info:
  role_name: docker
  author: S1117325
  description: Installeert Docker Engine (docker.io) en de Docker Compose v2 plugin
  license: MIT
  min_ansible_version: "2.14"
  platforms:
    - name: Ubuntu
      versions:
        - jammy
        - noble
  galaxy_tags:
    - docker
    - containers
dependencies: []
